# Generated by Django 5.2.17 on 2026-10-03 22:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("empresas", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Importacao",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "tipo",
                    models.CharField(
                        choices=[
                            ("extrato_ofx", "Extrato OFX"),
                            ("extrato_tabela", "Extrato CSV/Excel"),
                            ("titulos_pagar", "Contas a pagar"),
                            ("titulos_receber", "Contas a receber"),
                        ],
                        max_length=20,
                        verbose_name="tipo",
                    ),
                ),
                (
                    "nome_arquivo",
                    models.CharField(max_length=255, verbose_name="nome do arquivo"),
                ),
                (
                    "hash_sha256",
                    models.CharField(max_length=64, verbose_name="hash SHA-256"),
                ),
                (
                    "total_registros",
                    models.PositiveIntegerField(
                        default=0, verbose_name="registros importados"
                    ),
                ),
                (
                    "registros_ignorados",
                    models.PositiveIntegerField(
                        default=0, verbose_name="registros ignorados"
                    ),
                ),
                (
                    "criada_em",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="importado em"
                    ),
                ),
                (
                    "conta_bancaria",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="importacoes",
                        to="empresas.contabancaria",
                        verbose_name="conta bancária",
                    ),
                ),
                (
                    "empresa",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="importacoes",
                        to="empresas.empresa",
                        verbose_name="empresa",
                    ),
                ),
                (
                    "usuario",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="usuário",
                    ),
                ),
            ],
            options={
                "verbose_name": "importação",
                "verbose_name_plural": "importações",
                "ordering": ["-criada_em"],
            },
        ),
        migrations.CreateModel(
            name="MovimentacaoBancaria",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("data", models.DateField(verbose_name="data")),
                (
                    "valor",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Negativo = saída (débito); positivo = entrada (crédito).",
                        max_digits=14,
                        verbose_name="valor",
                    ),
                ),
                (
                    "historico",
                    models.CharField(max_length=500, verbose_name="histórico"),
                ),
                (
                    "documento",
                    models.CharField(
                        blank=True, max_length=60, verbose_name="documento"
                    ),
                ),
                (
                    "fitid",
                    models.CharField(
                        blank=True,
                        help_text="Identificador da transação no OFX.",
                        max_length=255,
                        verbose_name="FITID",
                    ),
                ),
                (
                    "tipo_transacao",
                    models.CharField(
                        blank=True, max_length=20, verbose_name="tipo de transação"
                    ),
                ),
                (
                    "linha_origem",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="linha/transação no arquivo"
                    ),
                ),
                (
                    "conta_bancaria",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="movimentacoes",
                        to="empresas.contabancaria",
                        verbose_name="conta bancária",
                    ),
                ),
                (
                    "empresa",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="movimentacoes",
                        to="empresas.empresa",
                        verbose_name="empresa",
                    ),
                ),
                (
                    "importacao",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="movimentacoes",
                        to="importers.importacao",
                        verbose_name="importação",
                    ),
                ),
            ],
            options={
                "verbose_name": "movimentação bancária",
                "verbose_name_plural": "movimentações bancárias",
                "ordering": ["data", "id"],
            },
        ),
        migrations.CreateModel(
            name="TituloFinanceiro",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "tipo",
                    models.CharField(
                        choices=[("pagar", "A pagar"), ("receber", "A receber")],
                        max_length=10,
                        verbose_name="tipo",
                    ),
                ),
                (
                    "parceiro_nome",
                    models.CharField(max_length=200, verbose_name="fornecedor/cliente"),
                ),
                (
                    "parceiro_cnpj_cpf",
                    models.CharField(
                        blank=True, max_length=14, verbose_name="CNPJ/CPF"
                    ),
                ),
                (
                    "numero_documento",
                    models.CharField(max_length=60, verbose_name="nº do documento"),
                ),
                (
                    "data_emissao",
                    models.DateField(blank=True, null=True, verbose_name="emissão"),
                ),
                ("data_vencimento", models.DateField(verbose_name="vencimento")),
                (
                    "data_pagamento",
                    models.DateField(blank=True, null=True, verbose_name="pagamento"),
                ),
                (
                    "valor",
                    models.DecimalField(
                        decimal_places=2, max_digits=14, verbose_name="valor"
                    ),
                ),
                (
                    "valor_pago",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=14,
                        null=True,
                        verbose_name="valor pago",
                    ),
                ),
                (
                    "historico",
                    models.CharField(
                        blank=True, max_length=500, verbose_name="histórico"
                    ),
                ),
                (
                    "linha_origem",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="linha no arquivo"
                    ),
                ),
                (
                    "empresa",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="titulos",
                        to="empresas.empresa",
                        verbose_name="empresa",
                    ),
                ),
                (
                    "importacao",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="titulos",
                        to="importers.importacao",
                        verbose_name="importação",
                    ),
                ),
            ],
            options={
                "verbose_name": "título financeiro",
                "verbose_name_plural": "títulos financeiros",
                "ordering": ["data_vencimento", "id"],
            },
        ),
        migrations.AddConstraint(
            model_name="importacao",
            constraint=models.UniqueConstraint(
                fields=("empresa", "hash_sha256"),
                name="arquivo_importado_uma_vez_por_empresa",
            ),
        ),
        migrations.AddIndex(
            model_name="movimentacaobancaria",
            index=models.Index(
                fields=["conta_bancaria", "data"], name="importers_m_conta_b_399fe6_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="movimentacaobancaria",
            index=models.Index(
                fields=["conta_bancaria", "fitid"],
                name="importers_m_conta_b_79def6_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="titulofinanceiro",
            index=models.Index(
                fields=["empresa", "tipo", "data_vencimento"],
                name="importers_t_empresa_fa86d8_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="titulofinanceiro",
            index=models.Index(
                fields=["empresa", "parceiro_cnpj_cpf"],
                name="importers_t_empresa_b33dc8_idx",
            ),
        ),
    ]
