# Generated by Django 5.2.17 on 2026-10-03 21:06

import django.core.validators
import django.db.models.deletion
import empresas.validadores
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Empresa",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "razao_social",
                    models.CharField(max_length=200, verbose_name="razão social"),
                ),
                (
                    "nome_fantasia",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="nome fantasia"
                    ),
                ),
                (
                    "cnpj",
                    models.CharField(
                        max_length=14,
                        unique=True,
                        validators=[empresas.validadores.validar_cnpj],
                        verbose_name="CNPJ",
                    ),
                ),
                (
                    "codigo_dominio",
                    models.CharField(
                        help_text="Código da empresa no Domínio Contabilidade.",
                        max_length=20,
                        unique=True,
                        verbose_name="código no Domínio",
                    ),
                ),
                ("ativa", models.BooleanField(default=True, verbose_name="ativa")),
                (
                    "criada_em",
                    models.DateTimeField(auto_now_add=True, verbose_name="criada em"),
                ),
                (
                    "atualizada_em",
                    models.DateTimeField(auto_now=True, verbose_name="atualizada em"),
                ),
            ],
            options={
                "verbose_name": "empresa",
                "verbose_name_plural": "empresas",
                "ordering": ["razao_social"],
            },
        ),
        migrations.CreateModel(
            name="ParametrosConciliacao",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "janela_dias",
                    models.PositiveSmallIntegerField(
                        default=3,
                        help_text="Diferença máxima de dias entre o banco e o título no match por valor + data.",
                        verbose_name="janela de datas (dias)",
                    ),
                ),
                (
                    "janela_dias_agrupamento",
                    models.PositiveSmallIntegerField(
                        default=30,
                        help_text="Janela usada nos matches N:1 (lote) e 1:N (parcelas).",
                        verbose_name="janela para agrupamentos (dias)",
                    ),
                ),
                (
                    "tolerancia_valor",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("10.00"),
                        help_text="Diferença máxima em reais (juros, multa, desconto, arredondamento).",
                        max_digits=12,
                        verbose_name="tolerância de valor (R$)",
                    ),
                ),
                (
                    "tolerancia_percentual",
                    models.DecimalField(
                        decimal_places=4,
                        default=Decimal("0.0500"),
                        help_text="Diferença máxima relativa ao valor do título (0,05 = 5%).",
                        max_digits=5,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0")),
                            django.core.validators.MaxValueValidator(Decimal("1")),
                        ],
                        verbose_name="tolerância percentual",
                    ),
                ),
                (
                    "score_conciliado",
                    models.PositiveSmallIntegerField(
                        default=80,
                        validators=[django.core.validators.MaxValueValidator(100)],
                        verbose_name="score mínimo para conciliação automática",
                    ),
                ),
                (
                    "score_possivel",
                    models.PositiveSmallIntegerField(
                        default=50,
                        validators=[django.core.validators.MaxValueValidator(100)],
                        verbose_name="score mínimo para possível correspondência",
                    ),
                ),
                (
                    "empresa",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="parametros",
                        to="empresas.empresa",
                        verbose_name="empresa",
                    ),
                ),
            ],
            options={
                "verbose_name": "parâmetros de conciliação",
                "verbose_name_plural": "parâmetros de conciliação",
            },
        ),
        migrations.CreateModel(
            name="ContaBancaria",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "banco_codigo",
                    models.CharField(max_length=10, verbose_name="código do banco"),
                ),
                (
                    "banco_nome",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="nome do banco"
                    ),
                ),
                ("agencia", models.CharField(max_length=20, verbose_name="agência")),
                ("conta", models.CharField(max_length=30, verbose_name="conta")),
                (
                    "descricao",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="descrição"
                    ),
                ),
                (
                    "conta_contabil_dominio",
                    models.CharField(
                        blank=True,
                        help_text="Conta do plano de contas do Domínio que representa este banco.",
                        max_length=30,
                        verbose_name="conta contábil no Domínio",
                    ),
                ),
                ("ativa", models.BooleanField(default=True, verbose_name="ativa")),
                (
                    "empresa",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="contas_bancarias",
                        to="empresas.empresa",
                        verbose_name="empresa",
                    ),
                ),
            ],
            options={
                "verbose_name": "conta bancária",
                "verbose_name_plural": "contas bancárias",
                "constraints": [
                    models.UniqueConstraint(
                        fields=("empresa", "banco_codigo", "agencia", "conta"),
                        name="conta_bancaria_unica_por_empresa",
                    )
                ],
            },
        ),
    ]
